<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>{{TargetFramework}}</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="{{AspNetCoreVersion}}" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="{{AspNetCoreVersion}}" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="{{AspNetCoreVersion}}" />
  </ItemGroup>

  <ItemGroup>
{{#if (eq DatabaseProvider "SqlServer")}}
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="{{AspNetCoreVersion}}" />
{{/if}}
{{#if (eq DatabaseProvider "PostgreSQL")}}
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="{{AspNetCoreVersion}}" />
{{/if}}
{{#if (eq DatabaseProvider "SQLite")}}
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="{{AspNetCoreVersion}}" />
{{/if}}
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\{{ProjectName}}.Base\{{ProjectName}}.Framework\{{ProjectName}}.Framework.csproj" />
    <ProjectReference Include="..\{{ProjectName}}.Common\{{ProjectName}}.Common.csproj" />
  </ItemGroup>
</Project>
